version: '2'

services:

  firefox:
    image: selenium/standalone-firefox-debug:3.8.1-dubnium
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - "4444:4444"
      - "5900:5900"
        
  surveys:
    image: memoer6/surveys:1.0.0
    ports:
      - "9001:9001"  
      
 # By default Compose sets up a single network for your app. Each container for a service joins the default network
 # and is both reachable by other containers on that network, and discoverable by them at a hostname identical
 # to the container name.           
        